services:
    sheer.browsers_icons.listener:
        class: sheer\browsers_icons\event\listener
        arguments:
            - %core.root_path%
            - @template
            - @dbal.conn
            - @config
            - @controller.helper
            - @sheer.browsers_icons.helper
            - @user
            - @auth
        tags:
            - { name: event.listener }
    sheer.browsers_icons.helper:
        class: sheer\browsers_icons\core\helper
        arguments:
            - %core.root_path%
